version: '3.6'
services:
  db:
    image: postgres:11-alpine
    shm_size: '256mb'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
       - "db-data:/var/lib/postgresql"
volumes:
  db-data:
